services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/shoppyglobe
      - PORT=3000
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=shoppyglobe
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: